version: '2.21'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # cache:
  #   image: redis
  #   restart: always
  #   volumes:
  #     - ./data/cache:/data
  
  rappitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  web:
    build: .
    command: sh -c "chmod +x /code/migrate.sh && ./wait-for-it.sh db:5432 -- sh /code/migrate.sh && /code/entrypoint.sh"
    # command: ["./wait-for-it.sh", "db:5432", "--",
    #         "sh"
    #         "python", "/code/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5555:5555"
    environment:
      - DJANGO_SETTINGS_MODULE=NeuraLearn.settings.prod
    env_file:
      - .env
    depends_on:
      - db
      # - cache

volumes:
  postgres_data: